Add files via upload
What is causing all this?
Traceback (most recent call last):
  File "ex43.py", line 22, in <module>
    my_object=my_life()
  File "ex43.py", line 13, in my_life
    my_choice == raw_input("> ")
NameError: global name 'my_choice' is not defined